### ISSUE TITLE
Weird space between module and function name

### ISSUE THREAD

**Issue by jchoude** [dipy/dipy_web#68]
I don't know if this is expected or not, but when we look at the API documentation, there is an additional space that is added between the next to last element of the path and the function name.

For example, see: https://dipy.org/documentation/1.0.0./reference/dipy.io/#dipy.io.streamline.load_tractogram

You can see that there is a space in
`dipy.io.streamline. load_tractogram`

at least when viewed in up to date Firefox.

**Comment by skoudoro** [comment]
same effect on Chrome (Windows). Thanks!
